---
sudo: false
dist: trusty
language: generic

services:
  - docker

install:
  - tools/travis-install-secrets.sh

script:
  - make compile SKIP_TESTS=false
  - make vm-images

deploy:
  provider: script
  script: tools/publish-packer-manifest.sh
