---
sudo: false
dist: trusty
language: generic

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

install:
  - tools/travis-install-secrets.sh

script:
  - make compile SKIP_TESTS=false

deploy:
  - provider: script
    skip_cleanup: true
    script: make vm-images
